repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [check, --select, I, --fix, --exit-non-zero-on-fix, --line-length=200, --ignore=F405, --ignore=F403]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
