# SPDX-FileCopyrightText: Copyright © 2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Maxime Delmas <maxime.delmas@idiap.ch>
# SPDX-License-Identifier: MIT
version = 1


[[annotations]]
path = "pyproject.toml"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "uv.lock"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".pre-commit-config.yaml"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".gitignore"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "examples/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "scripts/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Maxime Delmas <maxime.delmas@idiap.ch>"
SPDX-License-Identifier = "MIT"
